In [1]:
import numpy as np

### матрица передач

In [2]:
A = np.array([[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0],
              [0, 0, 0, 0, 0.6], [0, 0, 0, 0, 0]])

### вектор допустимого количества заявок в узлах

In [3]:
R = np.array([np.Inf, np.Inf, 20, np.Inf, np.Inf])

### вектор интенсивности обслуживания заявок

In [4]:
v = np.array([0.5, 0.3, 0.2, 2, 0.1])

### вектор количественного состава сети

In [5]:
m = np.array([3, 5, 10, 1, 20])

### вектор интенсивности внешнего входного потока

In [6]:
y = np.array([12, 15, 0, 0, 0])

In [7]:
print('A =', A, 'R =', R, 'y =', y,
      'm =', m, 'v =', v,
      sep='\n')

A =
[[0.  0.  1.  0.  0. ]
 [0.  0.  1.  0.  0. ]
 [0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  0.6]
 [0.  0.  0.  0.  0. ]]
R =
[inf inf 20. inf inf]
y =
[12 15  0  0  0]
m =
[ 3  5 10  1 20]
v =
[0.5 0.3 0.2 2.  0.1]


### вектор интенсивности входного потока

In [8]:
Y = y
TA = A.transpose()

for i in range(len(Y)):
    temp_array = np.zeros(5)
    temp_array[i] = sum(TA[:][i]*Y)
    Y = Y + temp_array

print(Y)

[12.  15.  27.  27.  16.2]


### вектор загрузки узлов

In [9]:
temp_array = np.zeros(5)

for i in range(len(Y)):
    temp_array[i] = Y[i]/(m[i]*v[i])

print(temp_array)

[ 8.  10.  13.5 13.5  8.1]


### эксперименты